import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navBar/NavBar";
import Footer from "@/components/footer/Footer";
import { fontManrope } from "@/lib/fonts";


export const metadata: Metadata = {
  title: "kotchmedia App",
  description: "Generated by kotchmedia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

        className={`bg-black flex flex-col justify-between h-screen ${fontManrope.variable}`}>
        <header className="container">
          <NavBar />
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
